
import React from 'react';
import { Translation, Language } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    title: "Contie",
    beta: "beta",
    welcome: "How can I support you today?",
    placeholder: "Type a message...",
    professional: "Professional Guidance",
    spiritual: "Spiritual Support",
    casual: "Casual Talk",
    suggestVerse: "Suggest Verse",
    history: "Chat History",
    newChat: "New Conversation",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    email: "Email Address",
    password: "Password",
    displayName: "Display Name",
    createAccount: "Create account",
    existingAccount: "Already have an account?",
    namePlaceholder: "Your full name",
    copied: "Copied to clipboard!",
    errorPrompt: "Please enter a message."
  },
  fr: {
    title: "Contie",
    beta: "bêta",
    welcome: "Comment puis-je vous aider aujourd'hui ?",
    placeholder: "Écrivez un message...",
    professional: "Orientation Professionnelle",
    spiritual: "Soutien Spirituel",
    casual: "Discussion Décontractée",
    suggestVerse: "Suggérer un Verset",
    history: "Historique",
    newChat: "Nouvelle Discussion",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    signOut: "Déconnexion",
    email: "Adresse e-mail",
    password: "Mot de passe",
    displayName: "Nom d'affichage",
    createAccount: "Créer un compte",
    existingAccount: "Vous avez déjà un compte ?",
    namePlaceholder: "Votre nom complet",
    copied: "Copié dans le presse-papiers !",
    errorPrompt: "Veuillez entrer un message."
  },
  rw: {
    title: "Contie",
    beta: "beta",
    welcome: "Ndagufasha nte uyu munsi?",
    placeholder: "Andika ubutumwa...",
    professional: "Inama z’Abahanga",
    spiritual: "Ubufasha bwa Roho",
    casual: "Ikiganiro Gisanzwe",
    suggestVerse: "Tanga umurongo",
    history: "Amateka",
    newChat: "Ikiganiro Gishya",
    signIn: "Injira",
    signUp: "Iyandikishe",
    signOut: "Sohoka",
    email: "Email yawe",
    password: "Ijambo ry'ibanga",
    displayName: "Izina rigaragara",
    createAccount: "Fungura konti",
    existingAccount: "Usanzwe ufite konti?",
    namePlaceholder: "Izina ryawe ryose",
    copied: "Byakoporowe!",
    errorPrompt: "Andika ubutumwa bwawe."
  }
};
